### ISSUE TITLE
lacking of <biest.hpp> file

### ISSUE THREAD

**Issue by gdwei123** [hiddenSymmetries/virtual-casing#6]
During the <make vc_testing> process, a error occured:  catastrophic error: cannot open source file "/root/virtual-casing-master/include/virtual-casing.hpp".

**Comment by dmalhotra** [comment]
Did you load the submodules?

**Comment by gdwei123** [comment]
Sir, do you mean the BIEST directory? I just download the v-c code from  github directly and after unzip the BIEST directory is empty. While, when I see the BIEST directory from github directly, the biest.hpp file did in the include. So, how can I load the submodules?  Just download the BIEST directory form github and put it into my v-c BIEST directory?

**Comment by dmalhotra** [comment]
I do not know if there is a way to do this using the web interface. It would be best if you use the command-line interface. Type the following commands in the terminal to get the repository and the submodules:

```
git clone https://github.com/hiddenSymmetries/virtual-casing.git
cd virtual-casing
git submodule init
git submodule update
```

**Comment by gdwei123** [comment]
Sir，I have finished all the steps you mentioned above. There is a new error occurred during the < make vc_testing >command: 
/root/virtual-casing/BIEST/include/sctl/common.hpp(82): internal error: assertion failed at: "declarator.c", line 4569 in make_bound_expr_referenceable_from_file_scope
         template <typename ValueType, Long DIM> using StaticArray = ValueType[DIM];
compilation aborted for /root/virtual-casing/test/virtual-casing.cpp (code 4)

**Comment by gdwei123** [comment]
belows are screen output during the <cmake .. > command
-- The C compiler identification is Intel 2021.9.0.20230302
-- The CXX compiler identification is Intel 2021.9.0.20230302
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/mpi/2021.9.0/bin/mpiicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/mpi/2021.9.0/bin/mpiicpc - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_intel_lp64.so;/opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_intel_thread.so;/opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_core.so;/opt/intel/oneapi/compiler/2023.1.0/linux/compiler/lib/intel64_lin/libiomp5.so;-lm;-ldl
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found LAPACK: /opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_intel_lp64.so;/opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_intel_thread.so;/opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_core.so;/opt/intel/oneapi/compiler/2023.1.0/linux/compiler/lib/intel64_lin/libiomp5.so;-lm;-ldl;-lm;-ldl
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Found FFTW: /home/software/fftw_double/include  found components: FLOAT_LIB DOUBLE_LIB LONGDOUBLE_LIB DOUBLE_OPENMP_LIB
-- FFTW_INCLUDE_DIR is /home/software/fftw_double/include
-- Found Python: /root/python3_virtual_env/bin/python3.10 (found suitable version "3.10.6", minimum required is "3") found components: Interpreter Development.Module
-- Python executable is /root/python3_virtual_env/bin/python3.10
-- Python Development Module found value is TRUE
-- Python header dirs are /usr/include/python3.10
-- Python library dirs are
-- Python version is 3.10.6
-- Submodule update
-- Local build detected. Set compilation flags accordingly.
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Success
-- Found OpenMP_C: -qopenmp (found version "5.0")
-- Found OpenMP_CXX: -qopenmp (found version "5.0")
-- Found OpenMP: TRUE (found version "5.0")
-- pybind11 v2.9.1
-- Performing Test HAS_INTEL_IPO
-- Performing Test HAS_INTEL_IPO - Failed
-- FFT DOUBLE FOUND
-- vc_testing include directories are /home/software/fftw_double/include;/home/software/fftw_double/include;/root/virtual-casing/include;/root/virtual-casing/BIEST/include
-- Configuring done (10.4s)
-- Generating done (0.1s)
-- Build files have been written to: /root/virtual-casing/build

**Comment by dmalhotra** [comment]
It seems to be an internal error in the compiler. Do you know if your compiler is configured correctly and supports C++11 standard? Can you post the result of the following command:

```
 /opt/intel/oneapi/mpi/2021.9.0/bin/mpiicpc -v
```

Alternatively, can you try using a different compiler, like GCC?

**Comment by gdwei123** [comment]
mpiicpc for the Intel(R) MPI Library 2021.9 for Linux*
Copyright Intel Corporation.
icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
icpc version 2021.9.0 (gcc version 11.3.0 compatibility)

**Comment by gdwei123** [comment]
GCC is ok for the <make vc_testing > and < python setup.py install > , and the virtual-casing is installed into my python lib. Thanks for your help.
